### ISSUE TITLE
Has anybody used Docker CE to deliver OGC web services?

### ISSUE THREAD

**Issue by heryk** [OneGeology/TechnicalDiscussion#10]
I've been recently using Docker (https://www.docker.com/) to deploy WMS applications (Geoserver, Mapserver, Mapproxy, etc...). A very powerful tool. Anyone has tried it out?

**Comment by KoalaGeo** [comment]
We use docker a fair bit, I've used it recently to setup a Geonetwork instance. @nmtoken soups be able to answer your question

**Comment by nmtoken** [comment]
I haven't used docker for WMS applications, but BGS has some experience of using it with GeoServer, I'll dig out the details.

Some questions/musings in no particular order:

- How much technical expertise do you need for docker (applies to other applications ~ including the standalone)

- What operating systems 

- How do you manage upgrading the system software, and maintaining the configuration files

- What problem (bottleneck?) does docker overcome?

- Where is the data?

- How does it compare with say MS4W for ease in setting up MapServer + Apache on a Windows server.  The examples I know about are Java based Applications on a Linux server.

- What overhead (if any) is there on performance for running an app on docker, as opposed natively?

**Comment by bgsmase** [comment]
I am closing this old issue as I doubt there is any need for special information here any more.
