### ISSUE TITLE
Remove old Polish service and layers

### ISSUE THREAD

**Issue by nmtoken** [OneGeology/TechnicalDiscussion#101]
As reported in [TIG 25](https://github.com/OneGeology/TechnicalDiscussion/wiki/TIG-Online-Meeting-2024-07-05) the Polish service currently listed in the portal has been replaced.  US will provide new service URL and layers but old service/layers should be removed

LAYERS

> POL PGI 1:1M Boundary
http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/58320b23-5127-4d62-b11f-7f6831ec4bde
> POL PGI 1:1M Faults, Overthrust
http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/7ad4e6af-a4bf-4445-9803-921286cae0b5
> POL PGI 1:1M Geological boundaries, National boundaries
http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/e9c1d9e1-87ba-4ff9-83bf-5c7b63157c37
> POL PGI 1:1M Geological units
http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/dadea649-e272-4e98-8976-3d915ca60b97
> POL PGI 1:1M Glaciation limits
http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/b392db86-b4be-4c5f-90d0-4757bfa52f5c
> POL PGI 1:1M Lakes
http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/00b745f6-3fe7-4d7e-a9a4-702a276979dd
> POL PGI 1:1M Rivers, Waters boundaries
http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/49b37059-240c-4970-a65e-c2771438375e

SERVICE

> Polish onegeology
http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/1d212bb061504036107341c77a8c71562aab4212

Affects layers from the following services: _https://onegeology.pgi.gov.pl/1GEconnector/_ and _https://onegeology.pgi.gov.pl/cgi-bin/mapserv?map=/u01/PGI_MOS_PL_Superficial_Geology/Poland.map&_

**Comment by nmtoken** [comment]
@Amayafv for info

**Comment by agalier** [comment]
Hello @nmtoken, I have completed the above tasks. Can you confirm to me that everything is ok for you ?

**Comment by nmtoken** [comment]
All removed, thanks.
