### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by KoalaGeo** [OneGeology/TechnicalDiscussion#11]
@heryk got a notification about adding slack to the technical discussion repository. Were you thinking of setting up a channel? Sounds like a good plan to me.

**Comment by nmtoken** [comment]
I saw the request, and tried to set up a onegeology slack workspace ~ I'm not sure what I've managed to achieve...

**Comment by heryk** [comment]
WoW! 2 years ago! I just noticed this issue. I think my addition to slack was accidental. But it could good. I currently have 2 other slack work groups that I use on a daily basis.

**Comment by nmtoken** [comment]
No longer seems to be relevant, closing for now.
