### ISSUE TITLE
Problem with polar maps not drawing completely

### ISSUE THREAD

**Issue by denevers** [OneGeology/TechnicalDiscussion#12]
When a map is drawn in polar projection, it "stops" drawing , or fail to draw polygons that crosses the date line (-180 / 180).  Seems to happen when the data is stored in 4326 or whatever flat projection.

**Comment by heryk** [comment]
The problem is related to vectors that overlap the meridian. Mapserver and Geoserver seem to have problems with that. The solution that was found to the circumpolar layer display bug by cutting the geology polygons along the 180 and prime meridians.
Cheers
Héryk

**Comment by heryk** [comment]
### Notes from Francis Aucoin on how to modifiy the geological polygon layer to correctly display data in epsg:3415.

** STEP 1 : **
In ArcMAP, make a line from two points that follow the 180 degree (long) with Construct Geodesic tool.
Long X (start) : 180
Lat Y (Start) : 45
Long X (Finish) : 0
Lat Y (Finish) : 45
This line is now available: LineCut2.shp (See geo\og\LineCut2.shp)

** STEP 2 : **
With Split Polygon tool, cut all features (in edition mode) with this line selected.
The .mxd must have another empty polygon shapefile to make this tool working.

** STEP 3 : **
Explode all multipart features with Explode Multipart Feature tool.
Save the edition. (See ipy_neurope_russia_onshore.shp & ipy_offshore.shp under geo\og)

**Comment by denevers** [comment]
I was convinced you just reprojected the dataset. This is much better.

@bgsmase  - I think you can close the issue

**Comment by nmtoken** [comment]
Do you still just have one layer, or do you have two layers, one per projection, and then group the layers so one will show?

**Comment by denevers** [comment]
One layer, the two layers solution is what I proposed earlier in our discussions but @heryk found a far better solution.
