### ISSUE TITLE
Bing Road and Bing Aerial base maps not showing in portal

### ISSUE THREAD

**Issue by nmtoken** [OneGeology/TechnicalDiscussion#16]
Neither of the Bing base-maps listed in the portal are currently providing any data, just get a blue screen.

Portal version is Portal v2020.0 

![Opera Snapshot_2020-08-20_131744_portal onegeology org](https://user-images.githubusercontent.com/1692891/90768660-f17bcf80-e2e6-11ea-935c-d7ca80130ba7.png)

**Comment by nmauroy** [comment]
Bings changed their api policy. I regenerate a key for staging and a key for production.
I will plan a new release to fix this issue.

**Comment by nicolas-m-brgm** [comment]
Fixed in production

**Comment by nicolas-m-brgm** [comment]
closing this one

**Comment by nicolas-m-brgm** [comment]
![image](https://user-images.githubusercontent.com/44254759/138227690-c75cc180-251d-48a0-80fc-a4f6965440a7.png)
