### ISSUE TITLE
Portal link to help is pointing at old version

### ISSUE THREAD

**Issue by nmtoken** [OneGeology/TechnicalDiscussion#17]
The go to documentation link in the portal (Portal v2020.0) is pointing at a deprecated version of the cookbook.

The link should now go to https://onegeology.github.io/documentation/portal.html

**Comment by nicolas-m-brgm** [comment]
Link has been chanded in staging. Ready for production

**Comment by nmtoken** [comment]
Correct in version portal 2020.0.1
