### ISSUE TITLE
FI_24948: Live portal using WMS 1.1.1 requests when WMS 1.3.0 exists

### ISSUE THREAD

**Issue by nicolas-m-brgm** [OneGeology/TechnicalDiscussion#19]
Originally posted as: https://forge.brgm.fr/issues/24948
Start date: | 23/01/2020

Description

Not sure if this is related to the closed issue https://forge.brgm.fr/issues/22220 (Staging portal using WMS 1.1.1 requests ~ closed as resolved )

> It appears the portal has reverted to using WMS version 1.1.1 requests instead of WMS 1.3.0 requests. I think we say now that a WMS version 1.3.0 only service is acceptable now, so this is a major issue.

> We used to say that we had to support WMS 1.1.1 and WMS 1.3.0 because of issues with GeoNetwork in harvesting from WMS 1.3.0 services, but that restriction no longer applies.

Just noticed when trying to debug an issue with the Arizona Geological Survey service.

Portal sends a GetCapabilities request like:

http://portal.onegeology.org/OnegeologyGlobal/proxy.jsp?url=http%3A%2F%2Fservices.azgs.az.gov%2Farcgis%2Fservices%2FOneGeology%2FAZGS_USGIN_Geology%2FMapServer%2FWMSServer%3Fservice%3DWMS%26request%3DGetCapabilities%26

Gets a WMS 1.3.0 response.

Then sends WMS 1.1.1 GetMap requests.

http://services.azgs.az.gov/arcgis/services/OneGeology/AZGS_Arizona_Geology/MapServer/WMSServer?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=US-AZ_AZGS_1M_Geologic_Age&SRS=EPSG%3A4326&STYLES=&WIDTH=578&HEIGHT=568&BBOX=-115.10004882812501%2C31.0448828125%2C-108.74995117187501%2C37.2851171875

I note too that the backdrop is also fetched as a WMS 1.1.1 request.

http://mapsref.brgm.fr/wxs/1GG/monde1GG?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=MONDE_ONEGEOLOGY_PROJECT&SRS=EPSG%3A4326&STYLES=&WIDTH=1112&HEIGHT=712&BBOX=-115.3509521484375%2C31.201171875%2C-109.2425537109375%2C35.1123046875

portrayal request is also not working, but this may be an issue at Arizona end...

http://services.azgs.az.gov/arcgis/services/OneGeology/AZGS_Arizona_Geology/MapServer/WMSServer?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=US-AZ_AZGS_1M_Lithology&SLD=http%3A%2F%2Fportal.onegeology.org%2FOnegeologyGlobal%2F%2Fslds%2F20200123_1579779870551_1.sld&SRS=EPSG%3A4326&STYLES=&WIDTH=

**Comment by nmtoken** [comment]
Issue persists in latest version Portal v2020.0.1

**Comment by nmtoken** [comment]
Related issue Staging portal using WMS 1.1.1 requests is reopened as the migrated: https://github.com/OneGeology/TechnicalDiscussion/issues/58

**Comment by nicolas-m-brgm** [comment]
Closing this one and answering on #58
