### ISSUE TITLE
FI_2481: Web Map Context (WMC) backdrop layers don't include service version

### ISSUE THREAD

**Issue by nicolas-m-brgm** [OneGeology/TechnicalDiscussion#21]
Originally posted as: https://forge.brgm.fr/issues/24841
Start date: | 16/12/2019

When saving a WMC file from the portal the backdrop layers don't include a service version, standard layers do.

As per below examples.

        <Layer queryable="false" hidden="false">
            <Server service="OGC:WMS" version="1.3.0">
                <OnlineResource xlink:type="simple" xmlns:xlink="http://www.w3.org/1999/xlink" 
                    xlink:href="https://map.bgs.ac.uk/arcgis/services/AGA/BGS_Groundwater/MapServer/WmsServer?" 
                />
            </Server>
            <Name>NGA_BGS_5M_Geology</Name>
            <Title>NGA_BGS_5M_Geology</Title>
            <FormatList>
                <Format current="true">image/png</Format>
            </FormatList>
            <StyleList>
                <Style current="true">
                    <Name/>
                    <Title>Default</Title>
                </Style>
            </StyleList>
        </Layer>

Example: standard data layer giving version

        <Layer queryable="false" hidden="false">
            <Server service="OGC:WMS">
                <OnlineResource xlink:type="simple" xmlns:xlink="http://www.w3.org/1999/xlink" 
                    xlink:href="http://ogc2.bgs.ac.uk/geoserver/OneG/ows"/>
            </Server>
            <Name>ARCTIC_NASA_BLUEMARBLE</Name>
            <Title>ARCTIC_NASA_BLUEMARBLE</Title>
            <FormatList>
                <Format current="true">image/jpeg</Format>
            </FormatList>
            <StyleList>
                <Style current="true">
                    <Name/>
                    <Title>Default</Title>
                </Style>
            </StyleList>
        </Layer>

Example backdrop layer without version

Need to have a version so that external WMC clients can make valid GetMap requests.

Should be version="1.3.0" for ARCTIC_NASA_BLUEMARBLE and ATA_USGS_LIMA layers

**Comment by nmtoken** [comment]
Still an issue with Portal v2020.0.1

**Comment by hramambazafy** [comment]
[Needs checking]
Bug is not reproduced

**Comment by nmtoken** [comment]
How did you generate the WMC to test that the bug can't be reproduced? it no longer seems possible (https://github.com/OneGeology/TechnicalDiscussion/issues/88)

**Comment by nmtoken** [comment]
I see that standard layers in generated WMC have service version numbers (in staging portal) as previously reported, but I also see that the backdrop layers are no longer included, so can't test the behaviour.  Testing against standard and Antarctic projections.

**Comment by nmtoken** [comment]
As behaviour can't be tested without backdrop layers included in the WMC will close this issue, but open a new one for the missing backdrops ~ https://github.com/OneGeology/TechnicalDiscussion/issues/89
