### ISSUE TITLE
FI_24069: Export to KML OneGeology logo is missing

### ISSUE THREAD

**Issue by nicolas-m-brgm** [OneGeology/TechnicalDiscussion#27]
Originally posted as: https://forge.brgm.fr/issues/24069
Start date: | 14/08/2019

![image](https://user-images.githubusercontent.com/44254759/95867604-9e178200-0d69-11eb-8f7e-817bfcfc0332.png)

**Comment by nmtoken** [comment]
Still an issue

**Comment by nicolas-m-brgm** [comment]
KML doesn't work anymore due to openlayer version upgrade. 
Work in progress to fix it

**Comment by hramambazafy** [comment]
[On staging]
The logo link pointed to a wrong url

**Comment by nmtoken** [comment]
Fixed and available on production
