### ISSUE TITLE
FI_24068: KML generated (incorrectly) includes Arctic and Antarctic backdrops

### ISSUE THREAD

**Issue by nicolas-m-brgm** [OneGeology/TechnicalDiscussion#28]
Originally posted as: https://forge.brgm.fr/issues/24068
Start date: | 14/08/2019

![image](https://user-images.githubusercontent.com/44254759/95867644-ab347100-0d69-11eb-866e-c8b1b501f037.png)

**Comment by nmtoken** [comment]
Still an issue in latest portal.

KML includes other backdrops for example export of initial page gives: 

    <?xml version="1.0" encoding="utf-8" ?>
    <kml xmlns="http://earth.google.com/kml/2.0">
        <Document>
            <name>OneGeology portal export</name>
            <Snippet>Display OneGeology datasets with Google earth</Snippet>
            <description/>
            <visibility>1</visibility>
            <open>1</open>
            <LookAt>
                <longitude>-9.492127156578638</longitude>
                <latitude>46.00833774914059</latitude>
                <altitude>0</altitude>
                <range>14221520.08547134</range>
                <tilt>-1.286133687015317e-014</tilt>
                <heading>-8.467838181803893</heading>
            </LookAt>
            <ScreenOverlay>
                <name>Logo OneGeology</name>
                <visibility>1</visibility>
                <open>0</open>
                <Icon>
                    <href>http://onegeology.brgm.fr/theme/img/BanniereOneGeology.png</href>
                </Icon>
                <color>ffffffff</color>
                <drawOrder>0</drawOrder>
                <overlayXY x="0" y="1" xunits="fraction" yunits="fraction"/>
                <screenXY x="0" y="1" xunits="fraction" yunits="fraction"/>
                <rotationXY x="0" y="0" xunits="fraction" yunits="fraction"/>
                <size x="0" y="0" xunits="fraction" yunits="fraction"/>
                <rotation>0</rotation>
            </ScreenOverlay>
            <GroundOverlay>
                <name>MONDE_ONEGEOLOGY_PROJECT</name>
                <Snippet/>
                <visibility>0</visibility>
                <open>0</open>
                <Icon>
                    <href>
                        http://mapsref.brgm.fr/wxs/1GG/monde1GG?&amp;VERSION=1.1.1&amp;REQUEST=GetMap&amp;SERVICE=WMS&amp;FORMAT=image/png&amp;width=1024&amp;height=1024&amp;STYLES=&amp;TRANSPARENT=TRUE&amp;SRS=EPSG:4326&amp;LAYERS=MONDE_ONEGEOLOGY_PROJECT </href>
                    <viewRefreshMode>onStop</viewRefreshMode>
                    <viewRefreshTime>5</viewRefreshTime>
                </Icon>
                <LatLonBox>
                    <north>48.41564493451794</north>
                    <south>45.57192031406902</south>
                    <east>5.287537680116226</east>
                    <west>0.703481821844738</west>
                </LatLonBox>
            </GroundOverlay>
            <GroundOverlay>
                <name>ARCTIC_NASA_BLUEMARBLE</name>
                <Snippet/>
                <visibility>0</visibility>
                <open>0</open>
                <Icon>
                    <href>
                        http://ogc2.bgs.ac.uk/geoserver/OneG/ows?VERSION=1.1.1&amp;REQUEST=GetMap&amp;SERVICE=WMS&amp;FORMAT=image/png&amp;width=1024&amp;height=1024&amp;STYLES=&amp;TRANSPARENT=TRUE&amp;SRS=EPSG:4326&amp;LAYERS=ARCTIC_NASA_BLUEMARBLE </href>
                    <viewRefreshMode>onStop</viewRefreshMode>
                    <viewRefreshTime>5</viewRefreshTime>
                </Icon>
                <LatLonBox>
                    <north>48.41564493451794</north>
                    <south>45.57192031406902</south>
                    <east>5.287537680116226</east>
                    <west>0.703481821844738</west>
                </LatLonBox>
            </GroundOverlay>
            <GroundOverlay>
                <name>ATA_USGS_LIMA</name>
                <Snippet/>
                <visibility>0</visibility>
                <open>0</open>
                <Icon>
                    <href>
                        http://ogc.bgs.ac.uk/cgi-bin/LIMA/ows?&amp;VERSION=1.1.1&amp;REQUEST=GetMap&amp;SERVICE=WMS&amp;FORMAT=image/png&amp;width=1024&amp;height=1024&amp;STYLES=&amp;TRANSPARENT=TRUE&amp;SRS=EPSG:4326&amp;LAYERS=ATA_USGS_LIMA </href>
                    <viewRefreshMode>onStop</viewRefreshMode>
                    <viewRefreshTime>5</viewRefreshTime>
                </Icon>
                <LatLonBox>
                    <north>48.41564493451794</north>
                    <south>45.57192031406902</south>
                    <east>5.287537680116226</east>
                    <west>0.703481821844738</west>
                </LatLonBox>
            </GroundOverlay>
            <GroundOverlay>
                <name>World_CGMW_50M_GeologicalUnitsOnshore</name>
                <Snippet/>
                <visibility>0</visibility>
                <open>0</open>
                <Icon>
                    <href>
                        http://mapsref.brgm.fr/wxs/1GG/CGMW_Bedrock_and_Structural_Geology?&amp;VERSION=1.1.1&amp;REQUEST=GetMap&amp;SERVICE=WMS&amp;FORMAT=image/png&amp;width=1024&amp;height=1024&amp;STYLES=&amp;TRANSPARENT=TRUE&amp;SRS=EPSG:4326&amp;LAYERS=World_CGMW_50M_GeologicalUnitsOnshore </href>
                    <viewRefreshMode>onStop</viewRefreshMode>
                    <viewRefreshTime>5</viewRefreshTime>
                </Icon>
                <LatLonBox>
                    <north>48.41564493451794</north>
                    <south>45.57192031406902</south>
                    <east>5.287537680116226</east>
                    <west>0.703481821844738</west>
                </LatLonBox>
            </GroundOverlay>
        </Document>
    </kml>

**Comment by nicolas-m-brgm** [comment]
Fixed and available in staging

**Comment by nicolas-m-brgm** [comment]
KML doesn't work anymore due to openlayer version upgrade. 
Work in progress to fix it
