### ISSUE TITLE
FI_23882: Investigate switching Portal to HTTPS

### ISSUE THREAD

**Issue by nicolas-m-brgm** [OneGeology/TechnicalDiscussion#29]
Originally posted as: https://forge.brgm.fr/issues/23882
Start date: | 08/07/2019

![image](https://user-images.githubusercontent.com/44254759/95867764-cbfcc680-0d69-11eb-979a-658171d7ab80.png)

**Comment by nicolas-m-brgm** [comment]
BGS need to ask for a certifcate

**Comment by nmtoken** [comment]
check with Patrick Bell? mechanisms...

**Comment by nicolas-m-brgm** [comment]
HTTPS is now activate in production

**Comment by bgsmase** [comment]
I'm not getting a response from either http://portal.onegeology.org or https://portal.onegeology.org at the moment...

**Comment by nicolas-m-brgm** [comment]
Can you clean your cache browser ?

**Comment by bgsmase** [comment]
Not browser cache issue (tried Control F5 reload, using a different browser which I don't use usually and using curl). I see http://portal.onegeology.org is responding but with the 301 Moved permanently to https://portal.onegeology.org and that isn't responding (Failed to connect to portal.onegeology.org port 443: Connection timed out).

**Comment by nmtoken** [comment]
I can't access it either, trying with new browser,  and curl, different networks... get 301 on http, but https have a timeout

`curl --head http://portal.onegeology.org
HTTP/1.1 301 Moved Permanently
Date: Fri, 21 Jan 2022 12:38:52 GMT
Location: https://portal.onegeology.org/
Content-Type: text/html; charset=iso-8859-1
Set-Cookie: BIGipServerpool_onegeology-web=638298304.20480.0000; path=/; Httponly
Set-Cookie: TS017f9c6b=01ce77d600fdf0b53af827986b98c1a4346dc69d1c8b2552a4125ec5bbc68d425489337a597c029c4e49f89f3d2ef6381fdeb2a3b7ace7132e76a0482f7a85e3d02b8f8f9f; Path=/
Transfer-Encoding: chunked`

`curl --head https://portal.onegeology.org
curl: (28) Failed to connect to portal.onegeology.org port 443 after 21140 ms: Timed out`

**Comment by nicolas-m-brgm** [comment]
It should be better now. It was only working on our network on friday morning

**Comment by bgsmase** [comment]
The Portal is appearing now but I am getting failures on a lot (not all) layers I try to add. For example:

- FR BRGM 1:1M Surface Geologic Units Lithology (GeoSciML WFS) (GeoSciML Portrayal) works
- World CGMW 1:50M Geological Units Onshore (default automatically displayed layer) works
- GBR BGS 1:625k Bedrock INSPIRE Age (GeoSciML WFS) (GeoSciML Portrayal) fails saying service not available. When I look at the web requests sent I see https://portal.onegeology.org/OnegeologyGlobal/proxyxml?url=http%3A%2F%2Fogc.bgs.ac.uk%3A80%2Fdigmap625k_gsml_insp_gs%2Fows%3FSERVICE%3DWMS%26request%3DGetCapabilities%26version%3D1.3.0%26 returns `message: Server returned HTTP response code: 403 for URL: http://ogc.bgs.ac.uk:80/digmap625k_gsml_insp_gs/ows?SERVICE=WMS&request=GetCapabilities&version=1.3.0&` although if I access http://ogc.bgs.ac.uk/digmap625k_gsml_insp_gs/ows?SERVICE=WMS&request=GetCapabilities&version=1.3.0& directly that returns the GetCapabilities response without error.
- JPN GSJ 1:2M Combined Bedrock and Superficial Geology and Age fails saying the layer is not available. In the web requests sent by the Portal https://portal.onegeology.org/OnegeologyGlobal/proxyxml?url=https%3A%2F%2Fonegeology-asia.org%2Fows%2FGSJ_Geological_Maps%2Fwms%3Fservice%3DWMS%26request%3DGetCapabilities%26version%3D1.3.0%26 returns  `message: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"` although directly accessing https://onegeology-asia.org/ows/GSJ_Geological_Maps/wms?service=WMS&request=GetCapabilities&version=1.3.0& returns a GetCapabilities response without error.

There are many other examples which fail. Note that in the above two examples the UK service is at an http URL and the Japan service is at an https URL. I guess mixed content is giving some  issues/

**Comment by nicolas-m-brgm** [comment]
Issues with our proxy. Is it better?

**Comment by bgsmase** [comment]
That does seem better to me. My browser (Firefox) warns that the connection is not secure because some content like images is not secure but I guess that is OK. I think if no other problems are found by the end of the day we can probably close this issue.
