### ISSUE TITLE
FI_23877: Make portal maintain hierarchy of geographic areas, not using parent areas from services.

### ISSUE THREAD

**Issue by nicolas-m-brgm** [OneGeology/TechnicalDiscussion#34]
Originally posted as: https://forge.brgm.fr/issues/23877
Start date: | 08/07/2019

![image](https://user-images.githubusercontent.com/44254759/95867947-00708280-0d6a-11eb-9901-328fd74850aa.png)

**Comment by nicolas-m-brgm** [comment]
What we did 

We are only using geographicarea keyword. Portal use an exported json file from https://unstats.un.org/unsd/methodology/m49/.

We are using m49 hierarchy by looking for the geographicarea keyword on the list.

In case portail does not find an entry we use a short exception list to make sure all services will still work.

`{
  "Democratic Republic of Congo": "Democratic Republic of the Congo",
  "Tanzania": "United Republic of Tanzania",
  "Southern Africa": "South Africa",
  "South Korea": "Republic of Korea",
  "Slovak Republic": "Slovakia",
  "United Kingdom": "United Kingdom of Great Britain and Northern Ireland",
  "Laos": "Lao People's Democratic Republic",
  "Vietnam": "Viet Nam",
  "Iran": "Iran (Islamic Republic of)",
  "Czech Republic": "Czechia",
  "Bosnia and Hercegovina": "Bosnia and Herzegovina",
  "Italia": "Italy",
  "The former Yugoslav Republic of Macedonia": "North Macedonia",
  "United States": "United States of America",
  "South Ameria": "Latin America and the Caribbean"
}`

Available on staging for testing : https://onegeology.brgm-rec.fr/mapClient/ (make sure to clean cache)
Let me know what do you think and if it was the behavior you expected.

**Comment by nmtoken** [comment]
Mostly as expected, some issues/inconsistencies.

- Could all lists be in alphabetical order (most seem to be)
- The 'World' list includes areas that I expected in other listings **'Rwanda and Burundi'** should be in Africa.  (though at the moment the service isn't working at all.); **Côte d'Ivoire** also is in Africa.  All the WCS should be in Europe, Andes should be in Latin America and the Caribbean.
- Latin America and the Caribbean is missing sub-divisions Caribbean, Central America, South America
- In world, South Victoria Land, should be a sub listing for Antarctica
- Commonwealth of Independent States should be a sub heading under Eurasia.
- Sub-Saharan Africa is missing sub divisions ~ Eastern Africa, Middle Africa, Southern Africa, Western Africa


Still not sure (something to discuss at next TIG perhaps) but if we keep to UN list all regions should be a sub heading under World.

**Comment by nicolas-m-brgm** [comment]
You are right. I forget to manage theses cases. it should be better now in staging.

We still need to take a look to the alphabetical order

**Comment by nicolas-m-brgm** [comment]
> Mostly as expected, some issues/inconsistencies.
> 
>     * Could all lists be in alphabetical order (most seem to be)
> 
>     * The 'World' list includes areas that I expected in other listings **'Rwanda and Burundi'** should be in Africa.  (though at the moment the service isn't working at all.); **Côte d'Ivoire** also is in Africa.  All the WCS should be in Europe, Andes should be in Latin America and the Caribbean.
> 
>     * Latin America and the Caribbean is missing sub-divisions Caribbean, Central America, South America
> 
>     * In world, South Victoria Land, should be a sub listing for Antarctica
> 
>     * Commonwealth of Independent States should be a sub heading under Eurasia.
> 
>     * Sub-Saharan Africa is missing sub divisions ~ Eastern Africa, Middle Africa, Southern Africa, Western Africa
> 
> 
> Still not sure (something to discuss at next TIG perhaps) but if we keep to UN list all regions should be a sub heading under World.

Fixed: 
* Could all lists be in alphabetical order (most seem to be)
* The 'World' list includes areas that I expected in other listings **'Rwanda and Burundi'** should be in Africa.  (though at the moment the service isn't working at all.); **Côte d'Ivoire** also is in Africa.  All the WCS should be in Europe, Andes should be in Latin America and the Caribbean.
* In world, South Victoria Land, should be a sub listing for Antarctica
* Commonwealth of Independent States should be a sub heading under Eurasia.
* Still not sure (something to discuss at next TIG perhaps) but if we keep to UN list all regions should be a sub heading under World.


To fix:
* Sub-Saharan Africa is missing sub divisions ~ Eastern Africa, Middle Africa, Southern Africa, Western Africa
* Latin America and the Caribbean is missing sub-divisions Caribbean, Central America, South America

**Comment by nicolas-m-brgm** [comment]
Ok for  Sub-Saharan Africa's sub divisions and Latin America and the Caribbean's sub divisions

**Comment by nmtoken** [comment]
Agree, fixed in staging.   

How should we tag for release? Milestone 2022_Q2 / 2022_R1 ?

**Comment by nmtoken** [comment]
fixed in production
