### ISSUE TITLE
FI_23873: Consider a better icon for the overview map pop-up

### ISSUE THREAD

**Issue by nicolas-m-brgm** [OneGeology/TechnicalDiscussion#36]
Originally posted as: https://forge.brgm.fr/issues/23873
Start date: | 08/07/2019

![image](https://user-images.githubusercontent.com/44254759/95868008-12522580-0d6a-11eb-83bf-ec36dbb2eec1.png)

**Comment by nmtoken** [comment]
Not sure if this was considered and rejected or considered and accepted...  The issue or the minutes don't mention which icon was used before.

Closing as new portal design has been accepted as improvement on previous design
