### ISSUE TITLE
FI_23871: Investigate link to separate window for GetFeatureInfo responses

### ISSUE THREAD

**Issue by nicolas-m-brgm** [OneGeology/TechnicalDiscussion#37]
Originally posted as: https://forge.brgm.fr/issues/23871
Start date: | 08/07/2019

![image](https://user-images.githubusercontent.com/44254759/95868039-1bdb8d80-0d6a-11eb-8428-146c1c89e97e.png)

**Comment by nmtoken** [comment]
Raised as a separate issue, but really this is the same as https://github.com/OneGeology/TechnicalDiscussion/issues/47
