### ISSUE TITLE
FI_23821: Propose Creative Commons licence for OneGeology documentation.

### ISSUE THREAD

**Issue by nicolas-m-brgm** [OneGeology/TechnicalDiscussion#38]
Originally posted as: https://forge.brgm.fr/issues/23821
Start date: | 28/06/2019

![image](https://user-images.githubusercontent.com/44254759/95868076-27c74f80-0d6a-11eb-85b8-e4aeb1c32a30.png)

**Comment by nmtoken** [comment]
Thought this had been actioned, but can't see any mention in OOG minutes

**Comment by nmtoken** [comment]
Documentation is available as [CC-BY-SA-4.0 License](https://github.com/OneGeology/documentation/blob/master/LICENSE)
