### ISSUE TITLE
FI_23818: Call for input on "Digital Twin" relevant standards

### ISSUE THREAD

**Issue by nicolas-m-brgm** [OneGeology/TechnicalDiscussion#39]
Originally posted as: https://forge.brgm.fr/issues/23818
Start date: | 28/06/2019

![image](https://user-images.githubusercontent.com/44254759/95868187-43caf100-0d6a-11eb-8f40-0671c290a8a7.png)

**Comment by nmtoken** [comment]
OneGeology Digital Twins working group was formed, but is inactive currently.  Closing this issue as not currently relevant.  May revisit.
