### ISSUE TITLE
FI_23806: Contact OGC and OpenLayers developers about adding WMC support

### ISSUE THREAD

**Issue by nicolas-m-brgm** [OneGeology/TechnicalDiscussion#40]
![image](https://user-images.githubusercontent.com/44254759/95868309-5e9d6580-0d6a-11eb-9044-799525e1d978.png)

**Comment by nmtoken** [comment]
Action originally from the [Austria TIG 2017 ](http://onegeology.org/docs/meetings/OneGeology-TIG-Minutes-Austria-230517.pdf).

For [Vancouver TIG 2018](http://onegeology.org/docs/meetings/TIG-Agreements-and-actions-Canada-2018.pdf)

> Action 8: FR to discuss with OGC, putting money towards getting an OpenLayers developer to put
WMC content back into OpenLayers. The next day OneGeology workshop on LOD requested that for
now (until OWSContext was supportable) the OneGeology portal continue to support WMC output.
# No discussion with OGC on the matter has so far taken place.
# The new portal was released with export support for WMC

FR has now left BRGM, so will assume that the action to discuss with OGC re OpenLayers support has now concluded.
