### ISSUE TITLE
FI_22214: Globe/Cesium view

### ISSUE THREAD

**Issue by nicolas-m-brgm** [OneGeology/TechnicalDiscussion#42]
Originally posted as: https://forge.brgm.fr/issues/22214
Start date: | 22/01/2019

![image](https://user-images.githubusercontent.com/44254759/95870027-4f1f1c00-0d6c-11eb-95bd-4f631cd03694.png)

**Comment by nmtoken** [comment]
This issue was discussed in a [TIG](https://github.com/OneGeology/TechnicalDiscussion/wiki/OneGeology-TIG-Face-to-Face-meeting-Friday-28th-June-2019-notes) and it was agreed to not have globe as the default view for now.  

> Discussed making the new globe view the default. At the moment it doesn’t perform well and there are some other issues with which services can display, there was a problem with getting GetFeatureInfo working so we can’t do it now. Meeting agreed that if the technical problems can be resolved, then the globe view would be a better starting view that would be more accessible to the general public.
