### ISSUE TITLE
FI_14040: Double check that the INSPIRE variant of the age and lithology generated SLD request match the final agreed HTTP-URI's

### ISSUE THREAD

**Issue by nicolas-m-brgm** [OneGeology/TechnicalDiscussion#52]
Originally: https://forge.brgm.fr/issues/14040

Start date: | 18/01/2016

![image](https://user-images.githubusercontent.com/44254759/95873239-010c1780-0d70-11eb-8c60-cfcccd44903c.png)
![image](https://user-images.githubusercontent.com/44254759/95873267-09645280-0d70-11eb-8337-41d5b9e18fb4.png)
![image](https://user-images.githubusercontent.com/44254759/95873289-0ff2ca00-0d70-11eb-8fa7-a1b91f2111cf.png)

**Comment by nmtoken** [comment]
Checking just now using the **1GE BGS 1M bedrock geologic unit age (GeoSciML Portrayal) ** layer.  The portal shows the analysis tool, and a selection was made for age as **Calymmian**.

The whole map changed colour which is not as expected. 

Using the Download SLD feature,we can see that the generated SLD, is not using any HTTP-URIs (or URNs), just:

    <?xml version="1.0" encoding="UTF-8"?>
    <sld:StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:sld="http://www.opengis.net/sld"
        xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.0.0">
        <sld:NamedLayer>
            <sld:Name>OGE_1M_bedrock_GeologicUnit_age</sld:Name>
            <sld:UserStyle>
                <sld:Name>onegeosld</sld:Name>
                <sld:Title/>
                <sld:FeatureTypeStyle>
                    <sld:Name>name</sld:Name>
                    <sld:FeatureTypeName>Feature</sld:FeatureTypeName>
                    <sld:SemanticTypeIdentifier>SemanticType[ANY]</sld:SemanticTypeIdentifier>
                    <sld:Rule>
                        <sld:PolygonSymbolizer>
                            <sld:Fill>
                                <sld:CssParameter name="fill">
                                    <ogc:Literal>#B6FF00</ogc:Literal>
                                </sld:CssParameter>
                                <sld:CssParameter name="fill-opacity">
                                    <ogc:Literal>1.0</ogc:Literal>
                                </sld:CssParameter>
                            </sld:Fill>
                        </sld:PolygonSymbolizer>
                    </sld:Rule>
                </sld:FeatureTypeStyle>
            </sld:UserStyle>
        </sld:NamedLayer>
    </sld:StyledLayerDescriptor>

This is a new issue in it's own right, but currently also means that this old issue can't be closed

**Comment by nmtoken** [comment]
Checking again today on live, and still have an issue when applying SLD. on attempting to restyle get message:

> Layer 1GE BGS 1M bedrock geologic unit age (GeoSciML Portrayal) has been removed from map because of an error during image loading

**Comment by nmtoken** [comment]
Fixed on staging, get SLD generated as:

    <?xml version="1.0" encoding="UTF-8"?>
    <sld:StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:sld="http://www.opengis.net/sld"
        xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.0.0">
        <sld:NamedLayer>
            <sld:Name>OGE_1M_bedrock_GeologicUnit_age</sld:Name>
            <sld:UserStyle>
                <sld:Name>onegeosld</sld:Name>
                <sld:Title/>
                <sld:FeatureTypeStyle>
                    <sld:Name>name</sld:Name>
                    <sld:FeatureTypeName>Feature</sld:FeatureTypeName>
                    <sld:SemanticTypeIdentifier>SemanticType[ANY]</sld:SemanticTypeIdentifier>
                    <sld:Rule>
                        <ogc:Filter>
                            <ogc:Or>
                                <ogc:PropertyIsEqualTo>
                                    <ogc:PropertyName>representativeAge_uri</ogc:PropertyName>
                                    <ogc:Literal>http://resource.geosciml.org/classifier/ics/ischart/Calymmian</ogc:Literal>
                                </ogc:PropertyIsEqualTo>
                                <ogc:PropertyIsEqualTo>
                                    <ogc:PropertyName>representativeAge_uri</ogc:PropertyName>
                                    <ogc:Literal>http://inspire.ec.europa.eu/codelist/GeochronologicEraValue/calymmian</ogc:Literal>
                                </ogc:PropertyIsEqualTo>
                                <ogc:PropertyIsEqualTo>
                                    <ogc:PropertyName>representativeAge_uri</ogc:PropertyName>
                                    <ogc:Literal>http://resource.geosciml.org/classifier/cgi/stratchart/Calymmian1</ogc:Literal>
                                </ogc:PropertyIsEqualTo>
                                <ogc:PropertyIsEqualTo>
                                    <ogc:PropertyName>representativeAge_uri</ogc:PropertyName>
                                    <ogc:Literal>http://inspire.ec.europa.eu/codelist/GeochronologicEraValue/calymmian1</ogc:Literal>
                                </ogc:PropertyIsEqualTo>
                                <ogc:PropertyIsEqualTo>
                                    <ogc:PropertyName>representativeAge_uri</ogc:PropertyName>
                                    <ogc:Literal>http://resource.geosciml.org/classifier/cgi/stratchart/Calymmian2</ogc:Literal>
                                </ogc:PropertyIsEqualTo>
                                <ogc:PropertyIsEqualTo>
                                    <ogc:PropertyName>representativeAge_uri</ogc:PropertyName>
                                    <ogc:Literal>http://inspire.ec.europa.eu/codelist/GeochronologicEraValue/calymmian2</ogc:Literal>
                                </ogc:PropertyIsEqualTo>
                                <ogc:PropertyIsEqualTo>
                                    <ogc:PropertyName>representativeAge_uri</ogc:PropertyName>
                                    <ogc:Literal>http://resource.geosciml.org/classifier/cgi/stratchart/Calymmian3</ogc:Literal>
                                </ogc:PropertyIsEqualTo>
                                <ogc:PropertyIsEqualTo>
                                    <ogc:PropertyName>representativeAge_uri</ogc:PropertyName>
                                    <ogc:Literal>http://inspire.ec.europa.eu/codelist/GeochronologicEraValue/calymmian3</ogc:Literal>
                                </ogc:PropertyIsEqualTo>
                                <ogc:PropertyIsEqualTo>
                                    <ogc:PropertyName>representativeAge_uri</ogc:PropertyName>
                                    <ogc:Literal>http://resource.geosciml.org/classifier/cgi/stratchart/Calymmian4</ogc:Literal>
                                </ogc:PropertyIsEqualTo>
                                <ogc:PropertyIsEqualTo>
                                    <ogc:PropertyName>representativeAge_uri</ogc:PropertyName>
                                    <ogc:Literal>http://inspire.ec.europa.eu/codelist/GeochronologicEraValue/calymmian4</ogc:Literal>
                                </ogc:PropertyIsEqualTo>
                            </ogc:Or>
                        </ogc:Filter>
                        <sld:PolygonSymbolizer>
                            <sld:Fill>
                                <sld:CssParameter name="fill">
                                    <ogc:Literal>#0026FF</ogc:Literal>
                                </sld:CssParameter>
                                <sld:CssParameter name="fill-opacity">
                                    <ogc:Literal>1.0</ogc:Literal>
                                </sld:CssParameter>
                            </sld:Fill>
                        </sld:PolygonSymbolizer>
                    </sld:Rule>
                </sld:FeatureTypeStyle>
            </sld:UserStyle>
        </sld:NamedLayer>
    </sld:StyledLayerDescriptor>

**Comment by nicolas-m-brgm** [comment]
Fixed
