### ISSUE TITLE
FI_21469: External service with Geosciml_lite_age_or_litho_queryable_2 keyword doesn't show thematic analysis tool

### ISSUE THREAD

**Issue by nicolas-m-brgm** [OneGeology/TechnicalDiscussion#53]
![image](https://user-images.githubusercontent.com/44254759/95873647-695af900-0d70-11eb-9b44-1459607c0b09.png)
![image](https://user-images.githubusercontent.com/44254759/95873667-6eb84380-0d70-11eb-95c1-6af26d84f700.png)
![image](https://user-images.githubusercontent.com/44254759/95873695-7546bb00-0d70-11eb-8276-9f02090ec7fb.png)
![image](https://user-images.githubusercontent.com/44254759/95873722-7bd53280-0d70-11eb-9969-64335f393335.png)
![image](https://user-images.githubusercontent.com/44254759/95873760-81327d00-0d70-11eb-9865-e7f626cf8394.png)

**Comment by nmtoken** [comment]
Originally: https://forge.brgm.fr/issues/21469

Start date: | 17/10/2018

**Comment by nicolas-m-brgm** [comment]
Fix in 2021.0.0
