### ISSUE TITLE
Import WCS is using WCS 1.0.0 version request, when should be using version 2.0.1

### ISSUE THREAD

**Issue by nmtoken** [OneGeology/TechnicalDiscussion#56]
As documented http://onegeology.org/docs/technical/CB6-HowToServe-a-OneGeology-WCS_v1.pdf 

`To have your coverage data visible in the portal the client will require that your WCS server software
supports the latest OGC WCS 2 standard, and can produce images in a format supported natively in
common web browsers, that is, with a MIME type of image/png, image/jpeg, or image/gif.`

Portal should be using WCS 2.0.1 to make requests, and not version 1.0.0.  Version 1.0.0 support was intended for catalogue harvesting only.

Example request like:

http://portal.onegeology.org/OnegeologyGlobal/proxyCesium.jsp?url=http%3A%2F%2F194.66.252.155%2Fgeoserver%2FOneGDev%2Fwcs%3F%26service%3DWCS%26version%3D1.0.0%26Coverage%3DOneGDev%3AWesternMed-MCol%26request%3DGetCoverage%26format%3Dimage%2Fpng%26CRS%3Depsg%3A4326%26bbox%3D-0.48958333%2C35.21874234%2C9.83125826%2C44.78958333%26width%3D500%26height%3D500&_=1603200949369

**Comment by nicolas-m-brgm** [comment]
Fixed on staging for testing.
WCS from catalog seems not working correctly, even on qgis. Is it working on qgis for you ?

**Comment by nmtoken** [comment]
Our ogc2.bgs.ac.uk geoserver service has a problem :( also affects the NSDIC (arctic back drop)

**Comment by nmtoken** [comment]
ogc2.bgs.ac.uk geoserver service has been fixed,

**Comment by nmtoken** [comment]
Fixed on production
