### ISSUE TITLE
Portal returns Whitelabel error

### ISSUE THREAD

**Issue by nmtoken** [OneGeology/TechnicalDiscussion#62]
![image](https://user-images.githubusercontent.com/1692891/114690977-22de5b00-9d0f-11eb-84cc-64d943a6cc8e.png)

> Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

> Wed Apr 14 11:13:45 CEST 2021
> There` was an unexpected error (type=Not Found, status=404).
> No message available

**Comment by nmtoken** [comment]
Reported by user and confirmed on Windows/Linux browsers where cache has been cleared.

**Comment by nicolas-m-brgm** [comment]
What is the url you are using ?

**Comment by nicolas-m-brgm** [comment]
Error on our side. Service has been restarted. It should works now
