### ISSUE TITLE
Portal update breaks mouse support on some old systems

### ISSUE THREAD

**Issue by nmtoken** [OneGeology/TechnicalDiscussion#63]
> , the issue is that in this latest version it is totally impossible to move the map displayed, in any direction;  no answer to the mouse moving !
	
> Only the zoom is functioning, but of no use as you can not spot any portion of the world map !

> Of course I did clean the cache...

Operating system is Vista.  Browsers used were Chrome and Firefox

**Comment by nicolas-m-brgm** [comment]
Probably browser versions :( do you know what was browser versions you was using ?


https://openlayers.org/en/latest/doc/tutorials/background.html:
`Renderers and Browser Support

By default, OpenLayers uses a performance optimized Canvas renderer.

OpenLayers runs on all modern browsers that support HTML5 and ECMAScript 5. This includes Chrome, Firefox, Safari and Edge. For older browsers and platforms like Internet Explorer (down to version 9) and Android 4.x, polyfills, the application bundle needs to be transpiled (e.g. using Babel) and bundled with polyfills for fetch, requestAnimationFrame, Element.prototype.classList, URL and TextDecoder.

The library is intended for use on both desktop/laptop and mobile devices, and supports pointer and touch interactions.`

**Comment by nmtoken** [comment]
Issue was reported through helpdesk.

Chrome and Firefox were reported as being used  (but not which versions), running on Vista (which is now out of date / no longer supported ~ support ended 2017).   Last supported Firefox on this platform was [52](https://www.mozilla.org/en-US/firefox/52.0/releasenotes/).  Firefox 52 did [support some HTML 5 and ECMAscript 7](https://html5test.com/compare/browser/firefox-52.html) features.

Issue has been raised here to allow the person who reported the issue to test further with their system.    I suggested testing against the different versions of OpenLayers on https://openlayers.org/ to see whether we can pin the issue to a particular version of OpenLayers, and then see what change between those versions.

**Comment by nmtoken** [comment]
> the application bundle needs to be transpiled

Can we provide  a transpiled version of the portal for legacy browsers and platforms?

**Comment by nicolas-m-brgm** [comment]
it is a complicated subject. I would suggest to encourage user to have their system up-to-date
