### ISSUE TITLE
Loading WMC by reference no longer works

### ISSUE THREAD

**Issue by nmtoken** [OneGeology/TechnicalDiscussion#64]
The documented way of loading a Web Map Context by reference no longer works.

Reference:
https://onegeology.github.io/documentation/portal.html#creating-and-using-web-map-context-wmc-documents

The following link should work:

http://portal.onegeology.org/OnegeologyGlobal/?language=eng&method=addExternalContext&url=http://ogc.bgs.ac.uk/wmc/IrelandGeologyEdited-wmc.xml

The WMC file exists

**Comment by nicolas-m-brgm** [comment]
I confirm it no longer works since a long time I think.

To match the latest developments, do you mind if we change the settings a bit to something like :

http://portal.onegeology.org/OnegeologyGlobal/serviceType=WMC&serviceUrl=http://ogc.bgs.ac.uk/wmc/IrelandGeologyEdited-wmc.xml

?

**Comment by nmtoken** [comment]
Changing the URL would be fine, just need to update the documentation

**Comment by nicolas-m-brgm** [comment]
ok great, we will work on it

**Comment by nicolas-m-brgm** [comment]
Behavior is back and available in staging https://onegeology.brgm-rec.fr/mapClient/?serviceType=WMC&serviceUrl=http://ogc.bgs.ac.uk/wmc/IrelandGeologyEdited-wmc.xml

**Comment by nmtoken** [comment]
Fixed in staging, reported fixed in live, but the following URL (following the URL pattern that works on staging) doesn't work on the live portal.

Works in staging:

> https://onegeology.brgm-rec.fr/mapClient/?serviceType=WMC&serviceUrl=http://ogc.bgs.ac.uk/wmc/IrelandGeologyEdited-wmc.xml

Doesn't work in live:

> http://portal.onegeology.org/OnegeologyGlobal/serviceType=WMC&serviceUrl=http://ogc.bgs.ac.uk/wmc/IrelandGeologyEdited-wmc.xml

Instead get White label error:

> Whitelabel Error Page
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> 
> Tue Jun 13 18:02:53 CEST 2023
> There was an unexpected error (type=Not Found, status=404).
> No message available

**Comment by nmtoken** [comment]
Confirming https://onegeology.brgm-rec.fr/mapClient/?serviceType=WMC&serviceUrl=http://ogc.bgs.ac.uk/wmc/IrelandGeologyEdited-wmc.xml now works on live portal
