### ISSUE TITLE
Loading WFS in search bar shows feature but fails to load

### ISSUE THREAD

**Issue by nmtoken** [OneGeology/TechnicalDiscussion#65]
Taking for example the _BRGM SIGAfrique Bedrock and Structural Geology_  service 
    
 > http://mapsref.brgm.fr/wxs/1GG/SIGAfrique_BRGM_Africa_Geology?

Adding to search bar shows WMS layers and WFS feature are available 

![image](https://user-images.githubusercontent.com/1692891/124562599-20cff800-de37-11eb-8daf-977b363c1750.png)

but trying to load a feature fails:

![image](https://user-images.githubusercontent.com/1692891/124563033-98058c00-de37-11eb-882f-ba068e440383.png)

WFS exists though.

**Comment by nmtoken** [comment]
looking at network traffic, a proxied DescribeFeatureType request is sent like:

> http://portal.onegeology.org/OnegeologyGlobal/proxyxml?url=http%3A%2F%2Fmapsref.brgm.fr%2Fwxs%2F1GG%2FSIGAfrique_BRGM_Africa_Geology%3Fservice%3DWFS%26request%3DDescribeFeatureType%26version%3D2.0.0%26TYPENAMES%3Dms%3AAFR_BRGM_10M_Faults

If I send an unproxied request like:

> http://mapsref.brgm.fr/wxs/1GG/SIGAfrique_BRGM_Africa_Geology?service=WFS&request=DescribeFeatureType&version=2.0.0&TYPENAMES=ms%3AAFR_BRGM_10M_Faults

it gives a response:

    <?xml version='1.0' encoding="UTF-8" ?>
    <schema
       targetNamespace="http://mapserver.gis.umn.edu/mapserver" 
       xmlns:ms="http://mapserver.gis.umn.edu/mapserver" 
       xmlns:xsd="http://www.w3.org/2001/XMLSchema"
       xmlns="http://www.w3.org/2001/XMLSchema"
       xmlns:gml="http://www.opengis.net/gml/3.2"
       elementFormDefault="qualified" version="0.1" >
      <import namespace="http://www.opengis.net/gml/3.2"
              schemaLocation="http://schemas.opengeospatial.net//gml/3.2.1/gml.xsd" />
      <element name="AFR_BRGM_10M_Faults" 
               type="ms:AFR_BRGM_10M_FaultsType" 
               substitutionGroup="gml:AbstractFeature" />
      <complexType name="AFR_BRGM_10M_FaultsType">
        <complexContent>
          <extension base="gml:AbstractFeatureType">
            <sequence>
              <element name="msGeometry" type="gml:GeometryPropertyType" minOccurs="0" maxOccurs="1"/>
            </sequence>
          </extension>
        </complexContent>
      </complexType>
    </schema>

**Comment by nicolas-m-brgm** [comment]
The service does not support geojson as output format. We will try to add this support to the service

**Comment by nmtoken** [comment]
could you parse the GetCapabilities and not show the service if it doesn't support GeoJSON?

**Comment by nicolas-m-brgm** [comment]
Good idea!

**Comment by nmtoken** [comment]
Seems fixed on production
