### ISSUE TITLE
Geographic Area and  Thematic lists not showing (Portal v2022.0.0)

### ISSUE THREAD

**Issue by nmtoken** [OneGeology/TechnicalDiscussion#73]
![image](https://user-images.githubusercontent.com/1692891/168024493-e74eb8a5-ac19-4d64-b533-2ae7ad1164b7.png)

Neither Geographic Area or Thematic lists are showing in the Add Datasets tab.

Tried on different browsers, and both http and https forms of the portal.  Dev portal is currently not available to test against

**Comment by nicolas-m-brgm** [comment]
Fixed, ElasticSearch was down

**Comment by nmtoken** [comment]
Working for https version of the portal, but not for http version

**Comment by nicolas-m-brgm** [comment]
it was due to a timeout because the catalog needed more than 1min30 to complete.

We added a cache to this request. This is a great thing for the user experience! The catalog is displayed immediately now.
The cache is restarted every 24 hours or after a server restart.
