### ISSUE TITLE
Import HTTPS WMS/WFS fails (Portal v2022.0.0 )

### ISSUE THREAD

**Issue by nmtoken** [OneGeology/TechnicalDiscussion#74]
Trying to add an HTTPS WMS or WFS  through the import functionality fails with error `Please try with a valid URL.`

![image](https://user-images.githubusercontent.com/1692891/168040052-ed2952a8-3ceb-47ee-b3ce-4725869015b8.png)

Tried on http and https versions of the portal.

Tested services work in QGIS with no issues

Probably same issue is use of search bar for tested services resulting in  `No result found` message

**Comment by nmtoken** [comment]
Portal sends a request like:
`https://portal.onegeology.org/OnegeologyGlobal/proxyxml?url=https%3A%2F%2Fogc.bgs.ac.uk%2Fcgi-bin%2FTFL-PSI%2Fows%3Fservice%3DWMS%26request%3DGetCapabilities%26version%3D1.3.0%26`

Resulting in a `HTTP/1.1 500 Erreur Interne de Servlet` response

**Comment by nicolas-m-brgm** [comment]
It works for me on HTTP but doesn't work on HTTPS. I opened an issue on brgm side to check SSL configuration

**Comment by nmtoken** [comment]
Trying to add `https://ogc.bgs.ac.uk/cgi-bin/BGS_BGS-HPA_Radon_Potential/ows?` to `http://portal.onegeology.org/OnegeologyGlobal/` doesn't work

Trying to add `https://ogc.bgs.ac.uk/cgi-bin/BGS_BGS-HPA_Radon_Potential/ows?` to `https://portal.onegeology.org/OnegeologyGlobal/` doesn't work

Trying to add `http://ogc.bgs.ac.uk/cgi-bin/BGS_BGS-HPA_Radon_Potential/ows?` to `https://portal.onegeology.org/OnegeologyGlobal/` works

Trying to add `http://ogc.bgs.ac.uk/cgi-bin/BGS_BGS-HPA_Radon_Potential/ows?` to `http://portal.onegeology.org/OnegeologyGlobal/` works

**Comment by nicolas-m-brgm** [comment]
Our technical team told me there is an issue with the certificate of the service

It can be check here https://www.ssllabs.com/ssltest/analyze.html?d=ogc.bgs.ac.uk&hideResults=on&latest => Chain issues | Incomplete

![image](https://user-images.githubusercontent.com/44254759/173571585-97bb7654-b17d-47da-8084-95c90ae167dc.png)


Is there something you can ask to check ?

**Comment by nmtoken** [comment]
Issue with certificate is now resolved (missing intermediary certificate)

**Comment by nmtoken** [comment]
Trying to add `https://ogc.bgs.ac.uk/cgi-bin/BGS_BGS-HPA_Radon_Potential/ows?` to `http://portal.onegeology.org/OnegeologyGlobal/`  now works

**Comment by nmtoken** [comment]
Trying to add `https://ogc.bgs.ac.uk/cgi-bin/BGS_BGS-HPA_Radon_Potential/ows?` to `https://portal.onegeology.org/OnegeologyGlobal/` now works
