### ISSUE TITLE
New KIGAM service won't work in portal

### ISSUE THREAD

**Issue by nmtoken** [OneGeology/TechnicalDiscussion#78]
KIGAM have a replacement (HTTPS only) service, (https://data.kigam.re.kr/mgeo/geoserver/OneGeology/wms?) that they would like registering in the portal, but it fails to load when tested in the portal.

Service works in desktop clients (ArcGIS/QGIS) and has a valid [GetCapabilities response](https://data.kigam.re.kr/mgeo/geoserver/OneGeology/wms?service=WMS&request=GetCapabilities)

Could this be an issue with spaces in the layer name `<Name>KOR KIGAM 1M Bedrock Geology</Name>`, &/or the SSL certificate, or something else?

I note that [SSL labs test gives a rating of F](https://www.ssllabs.com/ssltest/analyze.html?d=data.kigam.re.kr)

**Comment by nmtoken** [comment]
Previously thought this may be an issue with space in the layer name (though this is legal syntax), but after issue [74](https://github.com/OneGeology/TechnicalDiscussion/issues/74)  it is possible that the proxy has an issue with the SSL certificate for the service

**Comment by Sveouu** [comment]
This is really good to know, probably something I should check when looking at validation of any newly added services.

**Comment by nmtoken** [comment]
Reported fixed in staging, but loading (importing) as external service in staging fails for me with error  like:

![image](https://github.com/OneGeology/TechnicalDiscussion/assets/1692891/5a3b39df-5f9b-4690-8505-0949f9cce4cf)

Not sure what has attempted to be fixed, was it SSL issue or spaces in name issue

**Comment by nmtoken** [comment]
Issue is with spaces, fixed in a local copy, not yet deployed to staging

**Comment by hramambazafy** [comment]
[On staging]
This was a url format issue that misinterprets spaces

**Comment by nmtoken** [comment]
Tested as working on production

**Comment by bgsmase** [comment]
On further checking, although the display of the map has been fixed, getting the data for a point by clicking it still gives an error. Maybe the url format issue has been fixed for GetMap requests but not GetFeatureInfo requests? Please check and fix so the new service can be registered in the Portal and replace the no longer existing old service.

**Comment by bgsmase** [comment]
![image](https://github.com/OneGeology/TechnicalDiscussion/assets/5526663/4c633a8a-310f-4054-9075-56caf8387568)

**Comment by nmtoken** [comment]
Portal sends a request like:

    https://portal.onegeology.org/OnegeologyGlobal/proxyxml?url=https%3A//data.kigam.re.kr/mgeo/geoserver/OneGeology/ows%3FSERVICE%3DWMS%26SERVICE%3DWMS%26VERSION%3D1.3.0%26REQUEST%3DGetFeatureInfo%26FORMAT%3Dimage%252Fpng%26TRANSPARENT%3Dtrue%26QUERY_LAYERS%3DKOR%2520KIGAM%25201M%2520Bedrock%2520Geology%26LAYERS%3DKOR%2520KIGAM%25201M%2520Bedrock%2520Geology%26INFO_FORMAT%3Dtext%252Fhtml%26I%3D50%26J%3D50%26CRS%3DEPSG%253A4326%26STYLES%3D%26WIDTH%3D101%26HEIGHT%3D101%26BBOX%3D36.47577849030495%252C127.3765444457531%252C38.718212097883224%252C129.61897805333138&_=1704294218628

The actual GetFeatureInfo  request returns a result:

    https://data.kigam.re.kr/mgeo/geoserver/OneGeology/ows?SERVICE=WMS&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image/png&TRANSPARENT=true&QUERY_LAYERS=KOR%20KIGAM%201M%20Bedrock%20Geology&LAYERS=KOR%20KIGAM%201M%20Bedrock%20Geology&INFO_FORMAT=text/html&I=50&J=50&CRS=EPSG:4326&STYLES=&WIDTH=101&HEIGHT=101&BBOX=36.47577849030495,127.3765444457531,38.718212097883224,129.61897805333138 

though it should be noted that `TRANSPARENT=true&` is invalid syntax (wrong case)

**Comment by jghan2k** [comment]
I replaced the space in the lay name with '_'.
Now attribute info is searched normally.
The URL below works normally.

https://portal.onegeology.org/OnegeologyGlobal/proxyxml?url=https%3A//data.kigam.re.kr/mgeo/geoserver/OneGeology/ows%3FSERVICE%3DWMS%26SERVICE%3DWMS%26VERSION%3D1.3.0%26REQUEST%3DGetFeatureInfo%26FORMAT%3Dimage%252Fpng%26TRANSPARENT%3Dtrue%26QUERY_LAYERS%3DKOR_KIGAM_1M_Bedrock_Geology%26LAYERS%3DKOR_KIGAM_1M_Bedrock_Geology%26INFO_FORMAT%3Dtext%252Fhtml%26I%3D50%26J%3D50%26CRS%3DEPSG%253A4326%26STYLES%3D%26WIDTH%3D101%26HEIGHT%3D101%26BBOX%3D36.47577849030495%252C127.3765444457531%252C38.718212097883224%252C129.61897805333138&_=1704294218628

I hope that the Korean geological map will be serviced on the onegeology portal as soon as possible.

**Comment by jghan2k** [comment]
> Portal sends a request like:
> 
> ```
> https://portal.onegeology.org/OnegeologyGlobal/proxyxml?url=https%3A//data.kigam.re.kr/mgeo/geoserver/OneGeology/ows%3FSERVICE%3DWMS%26SERVICE%3DWMS%26VERSION%3D1.3.0%26REQUEST%3DGetFeatureInfo%26FORMAT%3Dimage%252Fpng%26TRANSPARENT%3Dtrue%26QUERY_LAYERS%3DKOR%2520KIGAM%25201M%2520Bedrock%2520Geology%26LAYERS%3DKOR%2520KIGAM%25201M%2520Bedrock%2520Geology%26INFO_FORMAT%3Dtext%252Fhtml%26I%3D50%26J%3D50%26CRS%3DEPSG%253A4326%26STYLES%3D%26WIDTH%3D101%26HEIGHT%3D101%26BBOX%3D36.47577849030495%252C127.3765444457531%252C38.718212097883224%252C129.61897805333138&_=1704294218628
> ```
> 
> The actual GetFeatureInfo request returns a result:
> 
> ```
> https://data.kigam.re.kr/mgeo/geoserver/OneGeology/ows?SERVICE=WMS&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image/png&TRANSPARENT=true&QUERY_LAYERS=KOR%20KIGAM%201M%20Bedrock%20Geology&LAYERS=KOR%20KIGAM%201M%20Bedrock%20Geology&INFO_FORMAT=text/html&I=50&J=50&CRS=EPSG:4326&STYLES=&WIDTH=101&HEIGHT=101&BBOX=36.47577849030495,127.3765444457531,38.718212097883224,129.61897805333138 
> ```
> 
> though it should be noted that `TRANSPARENT=true&` is invalid syntax (wrong case)

I replaced the space in the layer name with '_'.
Now attribute info is searched normally.
The URL below works normally.

https://portal.onegeology.org/OnegeologyGlobal/proxyxml?url=https%3A//data.kigam.re.kr/mgeo/geoserver/OneGeology/ows%3FSERVICE%3DWMS%26SERVICE%3DWMS%26VERSION%3D1.3.0%26REQUEST%3DGetFeatureInfo%26FORMAT%3Dimage%252Fpng%26TRANSPARENT%3Dtrue%26QUERY_LAYERS%3DKOR_KIGAM_1M_Bedrock_Geology%26LAYERS%3DKOR_KIGAM_1M_Bedrock_Geology%26INFO_FORMAT%3Dtext%252Fhtml%26I%3D50%26J%3D50%26CRS%3DEPSG%253A4326%26STYLES%3D%26WIDTH%3D101%26HEIGHT%3D101%26BBOX%3D36.47577849030495%252C127.3765444457531%252C38.718212097883224%252C129.61897805333138&_=1704294218628

I hope that the Korean geological map will be serviced on the onegeology portal as soon as possible.

**Comment by Amayafv** [comment]
Hello,
I've just changed the service to the new url. It seems to work properly. Could you please have a check?
cheers
Amaya

**Comment by nmtoken** [comment]
Service isn't showing up for me in the Portal Datasets menu, though service does have the correct cataloguing keywords.  If I search for it I find it though in correct geographic area, and then it is displaying correctly.   I've cleared my browser cache, so doesn't appear to be an artefact of the old list.

**Comment by nmtoken** [comment]
Assume the issue is that the service list is cached by the portal, so will check back in 24 hours (according to https://github.com/OneGeology/TechnicalDiscussion/issues/73).

**Comment by Amayafv** [comment]
![Capture d’écran 2024-01-22 173628](https://github.com/OneGeology/TechnicalDiscussion/assets/125989135/79ecda7b-20cd-4c4f-96a0-69f519e02845)

**Comment by Amayafv** [comment]
Hi @nmtoken 
It is not an automatic dataset, we have to search for.
But if you want it becomes an automatical layer let me know.

**Comment by nmtoken** [comment]
It is probably in scope to be an automatic layer (as KIGAM are Principal members);  it is in our to do list to work out a policy for which layers should be included as per https://github.com/OneGeology/TechnicalDiscussion/issues/35.  My comment (https://github.com/OneGeology/TechnicalDiscussion/issues/78#issuecomment-1904111979) however is not to do with automatic layers it's to do with the service showing in the list of services as per the below screen shot, it is missing from the list under Eastern Asia:

![2024-01-22 16 58 14 portal onegeology org e326b903eacd](https://github.com/OneGeology/TechnicalDiscussion/assets/1692891/ac978adc-fcf5-4162-bfd4-7c22c481729a)

**Comment by nmtoken** [comment]
KIGAM service now showing in layers list
