### ISSUE TITLE
KML export is still missing from portal

### ISSUE THREAD

**Issue by nmtoken** [OneGeology/TechnicalDiscussion#86]
As mentioned in comment on issue https://github.com/OneGeology/TechnicalDiscussion/issues/27 KML exporter wasn't working following OpenLayers upgrade.  Work was ongoing to fix it Oct 21, 2021, but still not available

**Comment by hramambazafy** [comment]
[On staging]
This feature was already available before, but with the upgrade of the openlayer, it no longer worked.

**Comment by nmtoken** [comment]
Fix available on production
