### ISSUE TITLE
Removal of deprecated service layers

### ISSUE THREAD

**Issue by nmtoken** [OneGeology/TechnicalDiscussion#93]
The following service/layers are no working and should be removed from the catalogue/portal layers listing:

> Ontario
>  CAN ON OGS 1M QUATERNARY GEOLOGY
>  CAN ON OGS 250K Diabase Dikes
>  CAN ON OGS 250K Iron Formations
>   CAN ON OGS 250K Major Structural Faults
>  CAN ON OGS 250K PRECAMBRIAN BEDROCK GEOLOGY

Service URLs were: 

    http://www.geologyontario.mndm.gov.on.ca:80/wmsconnector/com.esri.wms.Esrimap/CAN_ON_OGS_250K_BEDROCK_AND_STRUCTURAL_GEOLOGY
    
    https://www.geologyontario.mndm.gov.on.ca/wmsconnector/com.esri.wms.Esrimap/CAN_ON_OGS_1M_QUATERNARY_GEOLOGY

> Williston Basin
> CAN MGS 1:1M Cambrian Age - Williston Basin
> CAN MGS 1:1M Cretaceous Age - Williston Basin
> CAN MGS 1:1M Devonian Age - Williston Basin
> CAN MGS 1:1M Jurassic Age - Williston Basin
> CAN MGS 1:1M Mississippian Age - Williston Basin
> CAN MGS 1:1M Ordovician Age - Williston Basin
> CAN MGS 1:1M Permian Age - Williston Basin
> CAN MGS 1:1M Precambrian Age - Williston Basin
> CAN MGS 1:1M Silurian Age - Williston Basin
> CAN MGS 1:1M Tertiary Age - Williston Basin
> CAN MGS 1:1M Triassic Age - Williston Basin

Service URL(s) were: 

    http://geoapp2.gov.mb.ca/wmsconnector/com.esri.wms.Esrimap/CAN_MGS_WillistonBasin_Chronostrat_WMS?

> Red River Valley
> CAN MGS 1:250K Surficial Geology - Red River Valley
> CAN MGS SRTM 1:250K Digital Elevation Model - Red River Valley

Service URL(s) were: 

    http://geoapp2.gov.mb.ca/wmsconnector/com.esri.wms.Esrimap/CAN_MGS_RedRiverValley_WMS?

> Manitoba
> CA-MB MGS 1:1M Bedrock Age
> CA-MB MGS 1:1M Bedrock Geology
> CA-MB MGS 1:250k Quaternary Age
> CA-MB MGS 1:250k Surficial Geology
> CA-MB NASA 1:250k Digital Elevation Model
> CAN MGS 1:1M Bedrock Age - Manitoba
> CAN MGS 1:1M Bedrock Geology - Manitoba
> CAN MGS 1:1M Cambrian Age - Williston Basin
> CAN MGS 1:1M Cretaceous Age - Williston Basin
> CAN MGS 1:1M Devonian Age - Williston Basin
> CAN MGS 1:1M Jurassic Age - Williston Basin
> CAN MGS 1:1M Mississippian Age - Williston Basin
> CAN MGS 1:1M Ordovician Age - Williston Basin
> CAN MGS 1:1M Permian Age - Williston Basin
> CAN MGS 1:1M Precambrian Age - Williston Basin
> CAN MGS 1:1M Silurian Age - Williston Basin
> CAN MGS 1:1M Tertiary Age - Williston Basin
> CAN MGS 1:1M Triassic Age - Williston Basin
> CAN MGS 1:250K Quaternary Age - Manitoba
> CAN MGS 1:250K Surficial Geology - Manitoba
> CAN MGS 1:250k Surficial Geology - Red River Valley
> CAN MGS SRTM 1:250K Digital Elevation Model - Manitoba
> CAN NASA 1:250k Digital Elevation Model - Red River Valley

Service URL(s) were: 

    http://maps.gov.mb.ca/arcgis/services/MGS_Chronostratigraphy_Bedrock_and_Surficial_Geology/MapServer/WMSServer

> Newfoundland and Labrador
> CAN GSNL 1:1M Bedrock Geology
> CAN GSNL 1:1M Contacts / Faults
>  CAN GSNL 1:1M Surficial Geology

Service URL(s) were: 

    https://gis.geosurv.gov.nl.ca/wmsconnector/com.esri.wms.Esrimap/NAD27_MineralResources_NL

**Comment by Amayafv** [comment]
@nmtoken I've removed the services, can you please double check tomorrow if everything is ok?
Cheers,
Amaya

**Comment by nmtoken** [comment]
Most have now gone, but a few remain:

LAYER `CAN MGS 1:1M Bedrock Age - Manitoba` 
Catalogue record: http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/1e390c74-1c5d-4323-ad18-80e2fc694027

LAYER `CAN MGS 1:250K Quaternary Age - Manitoba`
Catalogue record: http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/c749bff1-9c77-4024-84ec-55dafa70ed98

Both provided through
SERVICE `MGS Chronostratigraphy` ( http://geoapp2.gov.mb.ca/wmsconnector/com.esri.wms.Esrimap/CAN_MGS_Chronostrat_WMS? ) 
Catalogue record: http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/2a641ac374277f7b6ef68083d9d7b151302297dc

LAYER `CAN MGS 1:1M Bedrock Geology - Manitoba`
Catalogue record: http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/1e390c74-1c5d-4323-ad18-80e2fc694027

Provided through:
SERVICE `MGS Bedrock Geology` ( http://geoapp2.gov.mb.ca/wmsconnector/com.esri.wms.Esrimap/CAN_MGS_Bedrock_Geology_WMS? )
Catalogue record: http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/d180cb9fbcdb5e39154b56feb21adfd9e07c5c

LAYER `CAN MGS 1:250K Surficial Geology - Manitoba`
Catalogue record: http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/69f6f227-b1e8-45a9-a31b-bd170371b186

Provided through:
SERVICE `MGS Surficial Geology` ( http://geoapp2.gov.mb.ca/wmsconnector/com.esri.wms.Esrimap/CAN_MGS_Surficial_Geology_WMS? )
Catalogue record:  http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/e11a18cf6b621a74d4e213c3de7423cc2f933b

LAYER `CAN MGS SRTM 1:250K Digital Elevation Model - Manitoba`
Catalogue record: http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/7f8c2613-0eda-4f5a-9424-8a991d65f6eb

Provided through:
SERVICE `MGS SRTM Digital Elevation Model` (
http://geoapp2.gov.mb.ca/wmsconnector/com.esri.wms.Esrimap/CAN_MGS_SRTM_DEM_WMS? )
Catalogue record: http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/1b91b3c5c2b582b7f4282b4f3374aa4c27f144db

LAYER `CAN MGS SRTM 1:250K Digital Elevation Model - Red River Valley`
Catalogue record:  http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/397b60ac-e0ee-436a-8d11-69e27ef018df

Provided through:
SERVICE `MGS Red River Valley SRTM Digital Elevation Model` (http://geoapp2.gov.mb.ca/wmsconnector/com.esri.wms.Esrimap/CAN_MGS_RedRiverValley_DEM_WMS?)
Catalogue record:  http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/dceaf4f58a29f0efdd1952764910191190fa5f

**Comment by Amayafv** [comment]
Hi @nmtoken can you check if now it works well?

**Comment by nmtoken** [comment]
Still showing in the portal datasets tab

**Comment by agalier** [comment]
Hi @nmtoken, can you please explain to us the procedure to check the presence or not of a layer/service?
For me everything is correct...

**Comment by nmtoken** [comment]
@agalier  If it's a layer I check to see if the layer still appears in both the catalogue and in the layers list (datasets tab) in the portal.

If it's a service (services are not listed in the layers list) I check the catalogue only.

So for example `MGS Red River Valley SRTM Digital Elevation Model` is still showing in the  catalogue ~ http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/dceaf4f58a29f0efdd1952764910191190fa5f 

![2024-06-17 14 51 10 onegeology-geonetwork brgm fr 4549b1a4b6c0](https://github.com/OneGeology/TechnicalDiscussion/assets/1692891/ba146dd9-2d21-4e60-9f4e-c267bf66bb45)

**Comment by agalier** [comment]
Hello @nmtoken, thank you very much for the information.
So I deleted the services. 
Can you confirm to me that this is ok for you ?

However I can't find the layers... Could you send me a screenshot of a layer still active ?

**Comment by nmtoken** [comment]
@agalier the reason for deleting the metadata and layer listings is because they are no longer active.  We don't want to advertise layers and services that are no longer active.

**Comment by nmtoken** [comment]
@agalier All metadata now gone, so the issue is now resolved, thanks
