### ISSUE TITLE
Update the Geography Marine layer in the Carte du monde Onegeology Service

### ISSUE THREAD

**Issue by nmtoken** [OneGeology/TechnicalDiscussion#97]
Update the `Geography Marine` layer in the `Carte du monde Onegeology Service` provided by BRGM (https://mapsref.brgm.fr/wxs/1GG/monde1GG?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities) 

Update to use latest version of the `ne_10m_geography_marine_polys` data from Natural Earth (NE) availble from [www.naturalearthdata.com/downloads/10m-physical-vectors/10m-physical-labels/](http://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-physical-labels/)

In addition modify the label `name` to read `East Sea / Sea of Japan` instead of  `Sea of Japan` for `ne_id` `1159115305`

**Comment by jfozzani** [comment]
Problem is solved, database and webache have been updated.
![onegg](https://github.com/OneGeology/TechnicalDiscussion/assets/99894740/89685772-4af7-4dd8-afcc-b5b0a7a7080d)
