### ISSUE TITLE
Removal of SEAMIC service layers

### ISSUE THREAD

**Issue by nmtoken** [OneGeology/TechnicalDiscussion#98]
The old SEAMIC hosted layers for East Africa are no longer available and need removing from the catalogue

SERVICE: `SEAMIC MGD EN Geology` (http://035a1a3.netsolvps.com/cgi-bin/SEAMIC_MGD_EN_Geology/ows?)
Record:  http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/b0e10e4634ac736b9a0d9c04a3cab4f591142f12

LAYER: `KEN MGD 1:2M Geology`
Record: http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/b44ed290-d8c4-4e27-88d2-82a63439fc60

SERVICE: `SEAMIC DGSM EN Geology` ( http://035a1a3.netsolvps.com/cgi-bin/SEAMIC_DGSM_EN_GEOLOGY/ows? )
Record:  http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/91c8966a6379c266967c0ac245286c44864d8d00

LAYER:  `UGA DGSM 1:2M Geology`
Record:  http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/70d95811-f7d9-4e12-af31-9d444902b4aa

SERVICE:  `SEAMIC GSE EN Geology` (http://035a1a3.netsolvps.com/cgi-bin/SEAMIC_GSE_EN_GEOLOGY/ows?)
Record: http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/d459a8ad05cd81aa45211d6347e92deb310b5278

LAYER: `ETH GSE 1:2M Geology`
Record:  http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/f1c44079-fbeb-4e8b-9df8-e351126ff779

SERVICE:  `SEAMIC GST EN Bedrock Geology` (http://035a1a3.netsolvps.com/cgi-bin/SEAMIC_GST_EN_Bedrock_Geology/ows?)
Record: http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/cdba0dae32448f05425030ced2f77789832a9111

LAYER:  `TZA GST 1:2M Bedrock Geology`
http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/5721d96e-1d3e-45af-a914-0bdc41140708

**Comment by Amayafv** [comment]
It's done, can you please check that is ok @nmtoken ?

**Comment by nmtoken** [comment]
Layers are still showing in the portal datasets list, and catalogue; possibly they are cached on the server

**Comment by Amayafv** [comment]
Ok I’ll see what happens,  can you please Adrien to github ?

De : James Passmore ***@***.***>
Envoyé : vendredi 7 juin 2024 14:14
À : OneGeology/TechnicalDiscussion ***@***.***>
Cc : Fuenzalida Velasco Amaya ***@***.***>; Assign ***@***.***>
Objet : Re: [OneGeology/TechnicalDiscussion] Removal of SEAMIC service layers (Issue #98)


Layers are still showing in the portal datasets list, and catalogue.

**Comment by nmtoken** [comment]
@agalier can you do these too?

**Comment by Amayafv** [comment]
@nmtoken hello James, please can you make a screenshot? then for us the question is more clear.

**Comment by nmtoken** [comment]
For example:

KEN MGD 1:2M Geology is still showing in layers list

![image](https://github.com/OneGeology/TechnicalDiscussion/assets/1692891/27a9c960-0110-49b4-8d50-c0777b87976a)

and is still in the catalogue:

http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/catalog.search#/metadata/b44ed290-d8c4-4e27-88d2-82a63439fc60

**Comment by agalier** [comment]
@nmtoken Done.
I'll let you check.

**Comment by nmtoken** [comment]
Metadata entries have now gone, but layers are still showing in the dataset / layers list.  I think there is some cache of this list, so may need manual refresh or otherwise will check when it natuarally refreshes

**Comment by agalier** [comment]
Sure enough, I actually think it's a cache issue. 
When we search for “Kenya”, the layer does not appear

![image](https://github.com/OneGeology/TechnicalDiscussion/assets/172043490/49fc714a-520a-41b6-983f-d6135f0e6366)

**Comment by nmtoken** [comment]
It's a cache on the server looking at: 

https://github.com/OneGeology/TechnicalDiscussion/issues/73#issuecomment-1158544069

so will wait 24 hours and test again

**Comment by nmtoken** [comment]
Entries have gone
